<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Loupedeck.LoupedeckHelperPlugin</RootNamespace>

    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputPath Condition="$(OS) == 'Windows_NT'">..\..\bin\$(Configuration)\win</OutputPath>
    <OutputPath Condition="$(OS) != 'Windows_NT'">../../bin/$(Configuration)/mac</OutputPath>

    <PluginApiDir Condition="$(OS) == 'Windows_NT'">C:\Program Files\Logi\LogiPluginService\</PluginApiDir>
    <PluginApiDir Condition="$(OS) != 'Windows_NT'">/Applications/Utilities/LogiPluginService.app/Contents/MonoBundle/</PluginApiDir>

    <PluginDir Condition="$(OS) == 'Windows_NT'">$(LocalAppData)\Logi\LogiPluginService\Plugins\</PluginDir>
    <PluginDir Condition="$(OS) != 'Windows_NT'">~/Library/Application\ Support/Logi/LogiPluginService/Plugins/</PluginDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PluginApi">
      <HintPath>$(PluginApiDir)PluginApi.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\LoupedeckSharedStateLib\LoupedeckSharedStateLib.csproj" />
  </ItemGroup>

  <Target Name="SetGitVersion" BeforeTargets="GenerateAssemblyInfo">
    <Exec Command="git -C &quot;$(MSBuildProjectDirectory)&quot; rev-parse --short HEAD" ConsoleToMSBuild="true" IgnoreExitCode="true">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitVersion" />
    </Exec>
    <PropertyGroup>
      <GitVersion Condition="'$(GitVersion)' == ''">unknown</GitVersion>
      <InformationalVersion>$(Version)+$(GitVersion)</InformationalVersion>
    </PropertyGroup>
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <PropertyGroup>
      <PluginLinkTarget>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)/../../bin/$(Configuration)'))</PluginLinkTarget>
    </PropertyGroup>
    <Exec Condition="$(OS) == 'Windows_NT'" Command="echo $(PluginLinkTarget) &gt; &quot;$(PluginDir)$(ProjectName).link&quot;" />
    <Exec Condition="$(OS) != 'Windows_NT'" Command="echo $(PluginLinkTarget) &gt; $(PluginDir)$(ProjectName).link" />
  </Target>

  <Target Name="CopyMetadata" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <MetadataFiles Include="metadata\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(MetadataFiles)" DestinationFolder="$(OutputPath)/../metadata" />
  </Target>

  <Target Name="PluginClean" AfterTargets="CoreClean">
    <Delete Condition="$(OS) == 'Windows_NT'" Files="$(PluginDir)$(ProjectName).link" />
    <Exec Condition="$(OS) != 'Windows_NT'" Command="rm -f $(PluginDir)$(ProjectName).link" />
    <RemoveDir Directories="$(OutputPath)/../metadata" />
  </Target>
</Project>
